spring:
  application:
    name: dubbo-registry-zookeeper-consumer-sample
server:
  port: 8081

dubbo:
  # Dubbo Protocol
  protocol:
    name: dubbo
   # Random port
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
logging:
  level:
    root: debug
