#设置镜像使用的基础镜像
FROM java:8
#设置镜像作者，可以是任意字符串
MAINTAINER YTQ
#编译镜像时运行的脚本
#容器启动时运行指定的命令，Dockerfile 中可以有多个 CMD 指令，但只有最后一个生效。CMD 可以被 docker run 之后的参数替换
CMD
#设置容器启动时运行的命令，Dockerfile 中可以有多个 ENTRYPOINT 指令，但只有最后一个生效。CMD 或 docker run 之后的参数会被当做参数传递给 ENTRYPOINT
ENTRYPOINT
#在容器中运行指定的命令
RUN
#将文件或目录声明为 volume
VOLUME /tmp/tomcat
#指定容器中的进程会监听某个端口，Docker 可以将该端口暴露出来
EXPOSE
#为后面的 RUN, CMD, ENTRYPOINT, ADD 或 COPY 指令设置镜像中的当前工作目录
WORKDIR
#设置环境变量，环境变量可被后面的指令使用
ENV
#将文件从 build context 复制到镜像  1.COPY src dest 2.COPY ["src", "dest"]
COPY
#与 COPY 类似，从 build context 复制文件到镜像。不同的是，如果 src 是归档文件（tar, zip, tgz, xz 等），文件会被自动解压到 dest
ADD spring-boot-docker-0.0.1-SNAPSHOT.jar springboot-docker.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/springboot-docker.jar"]